### PR TITLE
Returns original array-formatted data for file and db bundles

### PR DESCRIPTION
**Pull request by gilzow**
Fixes issue #100 
Creates copies of the original array-formatted data for file and db bundles to return to callers at the end of the method.

### CODE REVIEW

**Comment by ataylorme** [comment]
@elvismdev can you review this pull request?

**Comment by etherealite** [comment]
Commit [47029af](https://github.com/forumone/wp-cfm/pull/101/commits/47029af973d168101a488ebcae3de68e2a549595) negatively effects  diff viewer on the WP-Admin side of the plugin. 

Instead of displaying the diff in YAML format, it will be shown in the same format as the PHP `print_r` function. I made the bellow changes to the ajax request handler to fix the diff viewer.

```php
    function load_diff() {
        if ( current_user_can( 'manage_options' ) ) {
            $bundle_name = stripslashes( $_POST['data']['bundle_name'] );
            $comparison = WPCFM()->readwrite->compare_bundle( $bundle_name );
 
            // The pretty-text-diff.js will do its best on these print_r()s.
            if ( isset( $comparison['file'] ) ) {
                $comparison['file'] = print_r(WPCFM_Helper::convert_to_yaml($comparison['file'], false), true );
            }
            if ( isset( $comparison['db'] ) ) {
                $comparison['db'] = print_r( WPCFM_Helper::convert_to_yaml($comparison['db'], false), true );
            }

            echo json_encode( $comparison );
        }
        exit;
    }
```

**Review by elvismdev — CHANGES_REQUESTED** [review]
The warning bug was fixed in another thread with this PR https://github.com/forumone/wp-cfm/pull/124

**Comment by timnolte** [comment]
Seems to be fixed in another PR.

**Pull request closed without merging**
