### PR TITLE
[FEATURE] Yaml export format

### PR DESCRIPTION
**Pull request by mickaelperrin**
This PR allows to export configuration as YAML files.

Configurations options are deserialized and extracted from json to allow a better presentation of configuration in files and so a better versioning.

### CODE REVIEW

**Comment by mgibbs189** [comment]
@mickaelperrin thanks for contributing.

From what I can tell, this will break all existing instances of the plugin.

You're assuming that `WPCFM_CONFIG_FORMAT` is already defined. You'll need to check that this constant is set, and fallback to `json` when it's not.

```php
// Add a new method to class-helper.php
function get_config_format() {
    $format = defined( 'WPCFM_CONFIG_FORMAT' ) ? WPCFM_CONFIG_FORMAT : 'json';
    return apply_filters( 'wpcfm_config_format', $format );
}
```

**Comment by mickaelperrin** [comment]
Hey @mgibbs189, thanks for the awesome work you did already.

`WPCFM_CONFIG_FORMAT` is automatically defined as all other `WPCFM_` constants in https://github.com/forumone/wp-cfm/pull/67/commits/122ee6db25cd204f8fc3add673932dca98adcb56#diff-2db4a3dbfc9359e9c247a49c02c1cd8bR48

**Comment by mgibbs189** [comment]
Ah, sweet! I should've scrolled down below all that Symfony code in the diff 😂 

One more thing -- the assumption here is PHP 5.6.4+. I'm fine with bumping up the minimum version, but perhaps fail more gracefully for sites still on PHP 5.3 / 5.4. Thoughts?

**Comment by mickaelperrin** [comment]
Sure, will have a look at this and force JSON format if PHP requirement is not satisfied.

**Comment by mgibbs189** [comment]
One example: https://github.com/forumone/wp-cfm/pull/67/files#diff-eecd5db5dc83e39d7833bf1219ed64f0R96

array shorthand syntax was added in PHP 5.4. For those unlucky sites still on PHP 5.3, that **may** trigger a fatal error. Easiest fix would just be to swap out [] for array(), but there might be other PHP 5.4+ things to be aware of...

**Comment by mickaelperrin** [comment]
@mgibbs189 I ran a linter on the source code to check the compatibility issues. Except the short array syntax and the YAML library, everything is ok.

**Comment by mgibbs189** [comment]
Nice work @mickaelperrin, thank you! 👍

**Pull request merged**
