### PR TITLE
Ability to customize config url and dir

### PR DESCRIPTION
**Pull request by egamipeaks**
I need the ability to customize the directory where the json files are stored

### CODE REVIEW

**Comment by jmslbam** [comment]
+1

**Comment by mortona42** [comment]
This is doable with wp-cli.  Try:

wp config push BUNDLE --destination=DESTINATION.

You should see the path updated in the UI and if you type wp config bundles.

I would like to add this ability through the interface, I don't think it would take much.

Thanks for using wp-cfm!

**Comment by jmslbam** [comment]
- Does this mean the PR doesn't get merged because you want to add it to the GUI?

- Even if you want to add it to the UI. This means one first has to save the settings of WP-CFM before being able to export configs.
With this PR that becomes obsolete which imho I prefer. For example, I don't have to explain to all my colleagues that they need to do some extra step before starting with a project.
For WP-CLI, one has  to retype it at every import/export. Off course I could add it to my `wp-cli.yml` config file, but what if you don't use WP-CLI :smile: 

P.S. If you don't want a filter, a simple  is `defined ` check could be the alternative.
P.S. 2. The reason we don't use WP-CLI here is because we don't know all the bundle names by heart.
WP-CLI ACF has a list-prompt which asks you to choose a group field by number. 
https://github.com/hoppinger/advanced-custom-fields-wpcli/blob/master/ACF5_Command.php#L537
But that's a whole different PR ;)

I hope there will come a programmable way of

**Comment by egamipeaks** [comment]
@mortona42 not sure why this PR and your proposed future feature can't coexist. Personally I would prefer to set the path in my codebase though, or as @jmslbam mentioned, simply do a defined check on the constants.

**Comment by mortona42** [comment]
My mistake, I thought this was a feature request and not a PR (I'm new to github).  I'll be happy to review this code and merge it in, I will try to do that in the next few days.

**Pull request merged**
