### PR TITLE
Add pull --source and push --destination options.

### PR DESCRIPTION
**Pull request by mortona42**
Includes a patch for the diff bug and other updates to keep things working in the UI and other functions.

### CODE REVIEW

**Comment by mgibbs189** [comment]
Thanks @mortona42 - will try to test and approve early next week.

**Comment by mortona42** [comment]
Resolves https://github.com/forumone/wp-cfm/issues/40.

**Comment by arh1** [comment]
Howdy @mgibbs189 -- just checking in on this. Whenever you get a chance, let us know any comments, questions, or feedback on these features and we'll turn around any changes quickly. Thanks!

**Comment by mgibbs189** [comment]
Thanks @mortona42 @arh1 

Been swamped, but I'll push to wordpress.org after some more final testing

**Comment by arh1** [comment]
Awesome -- thanks, Matt. Happy to answer questions any time, and jump in on any bugs you find!

**Comment by mgibbs189** [comment]
Temporarily reverting this PR. Something in here is causing the UI to break

**Pull request merged**
