### PR TITLE
Fix Warning: Invalid argument supplied for foreach() on CLI

### PR DESCRIPTION
**Pull request by adnoh**
Fix Warning: Invalid argument supplied for foreach() in /wordpress/wp-content/plugins/wp-cfm/includes/class-wp-cli.php when using WP CLI (wp config diff all)

### CODE REVIEW

**Comment by adnoh** [comment]
@timnolte @elvismdev anybody there who can merge a pull request and get me rid of this annoying bug?

**Comment by timnolte** [comment]
@adnoh looks like we need to make some updates to the repo so that code reviewers get assigned and notified. I'll check with @elvismdev on this. Thanks!

**Review by elvismdev — APPROVED** [review]

**Comment by timnolte** [comment]
@elvismdev did you test this before merging it in? Has this broken the use of YAML with the CLI?

**Comment by elvismdev** [comment]
@timnolte Yes I did. Do you have a different experience while testing this or using the latest version of WP-CFM in a current project? If so, let's create a new bug issue and leave me there your reproduction steps so I can follow and I'll give it another shot. Thanks!

**Comment by timnolte** [comment]
@elvismdev you tested this with YAML files. The new check that was added in this PR is ` && !defined( 'WP_CLI' )` means the calls:
```php
$file_bundle = WPCFM_Helper::convert_to_yaml($file_bundle, false);
$db_bundle   = WPCFM_Helper::convert_to_yaml($db_bundle, false);
```
Won't get called when using WP-CLI.

**Comment by elvismdev** [comment]
@timnolte I've created a separate PR with this fix improved. https://github.com/forumone/wp-cfm/pull/124

**Pull request merged**
