### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by elvismdev**

### CODE REVIEW

**Comment by elvismdev** [comment]
@ataylorme I merged this, just tagging you in case you'd want to review this changelog.md format. Let me know if there's anything you'd like to change!

**Comment by ataylorme** [comment]
Looks good, thanks @elvismdev!

**Comment by ataylorme** [comment]
@elvismdev I see you tagged `1.6` on GitHub. Can you release to WordPress.org as well?

**Comment by elvismdev** [comment]
@ataylorme Yep! I'm on it via the GitHub action https://github.com/forumone/wp-cfm/blob/master/.github/workflows/wordpress-org-deploy.yml

**Pull request merged**
